[workspace]
resolver = "3"
members = []

[workspace.package]
edition = "2024"
license = "GPL-3.0"
categories = ["embedded", "hardware-support", "no-std"]
include = [
    "build.rs",
    "src/**/*",
    "Cargo.toml",
    "Cargo.lock",
    "LICENSE*",
    "README.md",
]
